<?php

/**
 * @file
 * Contains cntry_ste_dst_la_lb_wrd.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Component\Utility\Html;

/**
 * Implements hook_help().
 */
function cntry_ste_dst_la_lb_wrd_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.cntry_ste_dst_la_lb_wrd':
      $text = file_get_contents(__DIR__ . '/README.md');
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . Html::escape($text) . '</pre>';
      }
      else {
        // Use the Markdown filter to render the README.
        $filter_manager = \Drupal::service('plugin.manager.filter');
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $config = ['settings' => $settings];
        $filter = $filter_manager->createInstance('markdown', $config);
        return $filter->process($text, 'en');
      }
  }
  return NULL;
}

/**
 * Implements hook_theme().
 */
function cntry_ste_dst_la_lb_wrd_theme() {
  return [
    'cntry_ste_dst_la_lb_wrd' => [
      'variables' => [
        'country' => '',
        'state' => '',
        'district' => '',
        'lac' => '',
        'localbody' => '',
        'ward' => '',
      ],
    ],
    'country' => [
      'variables' => [
        'country' => '',
      ],
    ],
  ];
}
